### ISSUE TITLE
didnt get data in slack

### ISSUE THREAD

**Issue by pkhadka56** [jjethwa/icinga2-slack-notification#1]
I used your payload and it is not working. :(

I changed all the config file from slack-service-notification.sh but it is not working

**Comment by jjethwa** [comment]
Hi @pkhadka56 

Did you enable the new incoming webhook, set up the configs as detailed in readme, and make sure your Icinga server can access the slack webhook URL (firewall, etc)?

**Comment by pkhadka56** [comment]
@jjethwa Hi, thank you for your attention. I have followed your README and I get notification if I ran script itself from the command. but somehow I am not getting any alerts in slack itself. BTW our icingaweb2 is in https, does it matter?

**Comment by jjethwa** [comment]
Hi @pkhadka56 

Do your host objects have the vars.sla attribute defined?  If not, you'll have to modify the apply Notification rule that is shown in bullet #5 in the readme.  Let me know if that helps 🙂

**Comment by pkhadka56** [comment]
@jjethwa Sorry, after assigning vars.sla = "24x7" to one of the host object I got notification in slack.

Thanks.

**Comment by jjethwa** [comment]
@pkhadka56 

Great news!🙂

**Comment by pkhadka56** [comment]
@jjethwa last question why I am not getting addition details? it only shows the STATE. For example. it shows cpu load STATE is CRITICAL but didnt show how much load is.

**Comment by pkhadka56** [comment]
Sorry to bother and reopening again. I am not getting notification as I wanted. I wanted to get notification in slack as soon as STATE changes. Now it is sending notification base on time.

**Comment by jjethwa** [comment]
@pkhadka56 

You'll have to modify the script if you want the additional info.  My example script does not contain that as I feel it would be too much information for a Slack notification.

By default, notifications are executed immediately after state change so take a look at your configuration again :)

**Comment by pkhadka56** [comment]
thanks.
