### ISSUE TITLE
Downtime in Icinga2

### ISSUE THREAD

**Issue by ananthaa-advisory** [jjethwa/icinga2-slack-notification#11]
Hi @jjethwa ,

We are trying to put downtime to work from SLack.  We have a use case which will put a downtime for a full host and its related downtime in slack and we get notified on the same.

Do  you know of any API calls which will put a downtime for a single service check under a host. I have been looking on this from last  2 weeks and could not get any information. Can you help on this.

This is what I have and its not working:

> curl -u 'root:icinga' -s -k  -H 'Accept: application/json' -X POST "https://localhost:5665/v1/actions/schedule-downtime" -d '{ "type": "Host", "filter": "host.name==\"demo01.sample.com\"", "start_time": "'"$NOW"'", "end_time": "'"$END_TIME"'", "author": "testuser",  "comment": "hello", "fixed": true, "duration": 30}' | python -m json.tool | grep "Successfully scheduled downtime"

**Comment by jjethwa** [comment]
Hi @ananthaa-advisory 

In the filter section, you can do something like host.name == "dem01.sample.com" && service.name == "load"

**Comment by ananthaa-advisory** [comment]
Hi,

Yeah you are right. It worked out well..thanks :)
