### ISSUE TITLE
Icinga Director notifications are duplicated

### ISSUE THREAD

**Issue by UAnton** [jjethwa/icinga2-slack-notification#14]
Hello,
Notifications in Slack are duplicated.

**Comment by jjethwa** [comment]
Hi @UAnton 

Have you checked the configuration to make sure they are not duplicated Notification blocks?

**Comment by UAnton** [comment]
Hi @jjethwa 
I checked configs but don't find duplicated Notification blocks.

http://prntscr.com/kfn4gk

**Comment by jjethwa** [comment]
Hi @UAnton 

How did you set this up?  Via Director?

**Comment by UAnton** [comment]
Found problem! Have 2 users. My mistake! Sorry!
I need to be more careful.
Thanks!
