### ISSUE TITLE
License

### ISSUE THREAD

**Issue by simonft** [jjethwa/icinga2-slack-notification#15]
Thanks so much for this script.

Would you mind adding a license to the repository? I'd certainly feel more comfortable using this in a company setting if it's clear we're not violating copyright law using it (even given the obviously low chance of enforcement).

**Comment by jjethwa** [comment]
Hi @simonft 

No problem!  Thanks for bringing it to my attention.  I've added the LICENSE 😄 

https://github.com/jjethwa/icinga2-slack-notification/commit/2a3977930ffc94bc8b809f3199eec06decfceb48
