### ISSUE TITLE
additional state feature request

### ISSUE THREAD

**Issue by orangepeelbeef** [jjethwa/icinga2-slack-notification#16]
would be nice if the script understood  DOWNTIMESTART/DOWNTIMEEND
ACKNOWLEDGE

**Comment by jjethwa** [comment]
Hi @orangepeelbeef 

I'm on vacation for a few weeks and in a remote location, so internet access is spotty at best.  The script supports those states, you just need to modify the states section to have it triggered for those state types.  Check each of the configuration objects.

**Comment by orangepeelbeef** [comment]
Well, what happens in my setup is i get a notification of the downtime being set, but it doesn't say it is a downtime message, nor is it distinguishable from an alert.   Ack goes the same way, and there is usually a text field with who acked it and why that is not being displayed.   My configuration object triggers for the states, but the message we get is pretty much useless.

**Comment by jjethwa** [comment]
Hi @orangepeelbeef 

I'm sure the Notification object contains the necessary fields you need, but you might need to to extend the configuration for it and the slack notification shell script to include that in the slack payload as well.  Unfortunately, I really can't help until the end of August.  As it is, I could barely load this page to reply hehe

**Comment by orangepeelbeef** [comment]
=), i will take a stab at it and make a PR if I get anywhere

**Comment by jjethwa** [comment]
Thanks so much @orangepeelbeef. Also, love the username :smile:

**Comment by jjethwa** [comment]
Thanks again, @orangepeelbeef 😄
