### ISSUE TITLE
Notifications are not going to Slack

### ISSUE THREAD

**Issue by ananthaa-advisory** [jjethwa/icinga2-slack-notification#7]
HI @jjethwa ,

I am creating a new issue. Could you please help on this . Thanks in advance:

I integrated Icinga2/Slack for notifications purpose, however i am unable to see notifications going through:

I have attached the #icinga2 daemon -c , output for your visibility.

Here is the output:

[XXXXXXXX]# icinga2 daemon -C
information/cli: Icinga application loader (version: v2.6.0)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: 
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'slack' (in /etc/icinga2/conf.d/notifications.conf: 30:1-30:34) for type 'Notification' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 1 Zone.

notifications.conf file:

apply Notification "slack" to Host {
  import "slack-host-notification"
  users = [ "slack" ]
  user_groups = [ "slack1" ]
  interval = 2m
  assign where host.vars.notify_slack == true
  period = "24x7"

}

apply Notification "slack" to Service {
  import "slack-service-notification"
  users = [ "slack" ]
  user_groups = [ "slack1" ]
  interval = 2m
  assign where service.vars.notify_slack == true
  period = "24x7"
}

**Comment by jjethwa** [comment]
Hi @ananthaa-advisory 

Thanks for the new issue 😄   Do you mind adding one of your service or host conf files?  It looks like the assignment is not matching.  Perhaps due to the notify_slack not being defined?

**Comment by ananthaa-advisory** [comment]
Hi @jjethwa ,

So much thanks for your reply sir. So kind of you . 

Now the alerts are coming , however it is showing up only Critical alerts in my slack channel and the OK alerts are not coming through in the Slack channel.

I am worried if the OK alerts are  not coming through the Slack channel. Could you please help on this on where I am going wrong.

Attaching my services.conf:


```
/*
 * Service apply rules.
 *
 * The CheckCommand objects `ping4`, `ping6`, etc
 * are provided by the plugin check command templates.
 * Check the documentation for details.
 *
 * Tip: Use `icinga2 object list --type Service` to
 * list all service objects after running
 * configuration validation (`icinga2 daemon -C`).
 */

/*
 * This is an example host based on your
 * local host's FQDN. Specify the NodeName
 * constant in `constants.conf` or use your
 * own description, e.g. "db-host-1".
 */

/*
 * These are generic `ping4` and `ping6`
 * checks applied to all hosts having the
 * `address` resp. `address6` attribute
 * defined.
 */
apply Service "ping4" {
  import "generic-service"

  check_command = "ping4"

  assign where host.address
}

apply Service "ping6" {
  import "generic-service"

  check_command = "ping6"

  assign where host.address6
}

/*
 * Apply the `ssh` service to all hosts
 * with the `address` attribute defined and
 * the custom attribute `os` set to `Linux`.
 */
apply Service "ssh" {
  import "generic-service"

  check_command = "ssh"
  vars.notify_slack=true
  assign where (host.address || host.address6) && host.vars.os == "Linux"
}



apply Service for (http_vhost => config in host.vars.http_vhosts) {
  import "generic-service"

  check_command = "http"
vars.notify_slack=true
  vars += config
}

apply Service for (disk => config in host.vars.disks) {
  import "generic-service"

  check_command = "disk"

  vars += config
}

apply Service "icinga" {
  import "generic-service"

  check_command = "icinga"

  assign where host.name == NodeName
}


apply Service "load" {
  import "generic-service"

  check_command = "load"

  /* Used by the ScheduledDowntime apply rule in `downtimes.conf`. */
  vars.backup_downtime = "02:00-03:00"

  assign where host.name == NodeName
}

apply Service "procs" {
  import "generic-service"

  check_command = "procs"

  assign where host.name == NodeName
}

apply Service "swap" {
  import "generic-service"

  check_command = "swap"

  assign where host.name == NodeName
}

apply Service "users" {
  import "generic-service"

  check_command = "users"

  assign where host.name == NodeName
}

```

**Comment by jjethwa** [comment]
Hi @ananthaa-advisory 

Good news about getting some notifications 😄   Are the correct States and Types that you want notifications listed in: https://github.com/jjethwa/icinga2-slack-notification/blob/master/slack-service-notification.conf

Also, check the slack user conf.  Does it have the States and Types listed?
Example:

```
object User "slack" {
  import "generic-user"

  display_name = "slack alerts"
  groups = [ "somegroup" ]
  states = [ OK, Warning, Critical ]
  types = [ Problem, Recovery ]

  email = "my@email.com"
}
```

**Comment by ananthaa-advisory** [comment]
Hi @jjethwa ,

Do you know , how to acknowledge,schedule downtime from SLack channel to Icinga2 itself. I am trying to deploy that . Could you please help.

I already tried implementing SPJMurray method and could not go anywhere. if you have some solution , could you tell please ? Thanks

Aravind

**Comment by jjethwa** [comment]
Hi @ananthaa-advisory 

That functionality would require a bot so it could listen for commands on a channel and send them to Icinga2 using it's API.  I don't know if there are any out there or at least I haven't run into one yet 😃

**Comment by ananthaa-advisory** [comment]
Thanks sir :)

I do have a BOT and have created a slash command from Slack. But i could not get an API up and running from Icinga2 . :(

I have a downtime script , which will schedule downtime in Icinga2 , written in Bash.,however, it uses three arguments.

we have integrated Ansible with Slack environment.

I am just thinking of how to execute this Bash script with three arguments via Ansible from the Slack channel itself. lets see . Hoping for best :)

**Comment by jjethwa** [comment]
@ananthaa-advisory 

That's awesome!  Once you get it working, maybe you can push it to git 😄 

Have you followed the steps to get the API running?  https://www.icinga.com/docs/icinga2/latest/doc/12-icinga2-api/

**Comment by ananthaa-advisory** [comment]
Hey @jjethwa ,

we can now have ability to schedule downtime,acknowledgement for Icinga2 from Slack channel itself.

I have a downtime script which will schedule downtime for complete service check and host., 
Second, Have Ansible installed in a separate server. Download Ansible module for Hubot, where you can execute bot commands for Ansible from Slack channel.

Thanks much , I really had a wonderful conversation with you ! Special thanks for your code on Slack notifications in Github , Great minds :)

**Comment by jjethwa** [comment]
That's awesome news, @ananthaa-advisory , and thanks for the tip.  Glad I could help!  Was great chatting with you 😄

**Comment by ananthaa-advisory** [comment]
Hi @jjethwa ,

Sorry to disturb you again. I have another doubt.
Question 1:

For not Receiving notifications, you said that we need to add a parameter in the services.conf file

 vars.notify_slack=true, Do we need to add this parameter on all service checks on a services.conf file ?

Question 2:

I have now about 500 + plus hosts, how do I add this paramater " vars.notify_slack=true" , Is  there a way to declare this parameter globally , so that all my client services.conf file would take this paramter and notify Slack channel.

Thanks in advance

Best
Aravind

**Comment by jjethwa** [comment]
Hi @ananthaa-advisory 

NP at all!

That parameter seems to be added by you and looking at your config, it would need to be set on every service you want.  You can set it in generic-service Service template definition if you want it set by default since your service definitions import it.  Hope that makes sense 😄

**Comment by ananthaa-advisory** [comment]
Thanks @jjethwa .

I will open a new issue to you :)
